Repository LoginRadius/business-email-validator, pull requests merged in 2020-10, with the labels that each got.

#2 Add some 10 Minute Mail accounts
  src/freeEmailService.json
Labels: In Review

#4 removed duplicates and sync src main list to js sdk
  dist/js/businessEmailValidator.js
  dist/js/businessEmailValidator.min.js
  src/freeEmailService.json
Labels: In Review, Ready for Merge

#16 Added domains from temporary mail sites
  src/freeEmailService.json
Labels: In Review

#23 Added csharp wrapper.
  dist/csharp/EmailValidator.cs
Labels: In Review, Ready for Merge

#28 Added Java wrapper
  dist/java/BusinessEmailValidator.java
Labels: In Review, Ready for Merge

#22 Added More Business Email Address
  dist/js/businessEmailValidator.js
  src/freeEmailService.json
Labels: Ready for Merge, hacktoberfest

#13 Custom Onet hostnames
  src/freeEmailService.json
Labels: ineligible

#24 Add Tutanota email service
  src/freeEmailService.json
Labels: In Review

#20 solves Create wrapper for business-email-validator in Python #7
  .DS_Store
  dist/.DS_Store
  dist/python/businessEmailValidator.py
Labels: Ready for Merge

#29 Create wrapper for business-email-validator in Go
  dist/go/business-email-validator.go
Labels: hacktoberfest-accepted

#33 Added trashmail domains
  src/freeEmailService.json
Labels: hacktoberfest-accepted

#35 Delete duplicate emails
  src/freeEmailService.json
Labels: hacktoberfest-accepted
