Repository LoginRadius/business-email-validator, pull requests merged in 2021-09, with the labels that each got.

#31 Add Dart wrapper for businessEmailValidator
  README.md
  dist/dart/README.md
  dist/dart/businessEmailValidator.dart
  dist/dart/main.example.dart
Labels: In Review, hacktoberfest-accepted

#18 feat: implement cpp wrapper
  dist/cplusplus/README.md
  dist/cplusplus/json.hpp
  dist/cplusplus/test.json
  dist/cplusplus/tests
  dist/cplusplus/tests.cpp
  dist/cplusplus/wrapper.hpp
Labels: Changes Requested

#21 Wrapper for PHP + list update
  README.md
  dist/php/businessEmailValidator.php
  src/freeEmailService.json
Labels: hacktoberfest-accepted
